2021-11-09 21:27:43,773 INFO    MainThread:1436004 [wandb_setup.py:_flush():71] setting env: {}
2021-11-09 21:27:43,773 INFO    MainThread:1436004 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-09 21:27:43,773 INFO    MainThread:1436004 [wandb_init.py:_log_setup():357] Logging user logs to /home/ssc255/nlp/ner_experiments/src/wandb/run-20211109_212743-2wvtd0ey/logs/debug.log
2021-11-09 21:27:43,773 INFO    MainThread:1436004 [wandb_init.py:_log_setup():358] Logging internal logs to /home/ssc255/nlp/ner_experiments/src/wandb/run-20211109_212743-2wvtd0ey/logs/debug-internal.log
2021-11-09 21:27:43,773 INFO    MainThread:1436004 [wandb_init.py:init():390] calling init triggers
2021-11-09 21:27:43,773 INFO    MainThread:1436004 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2021-11-09 21:27:43,773 INFO    MainThread:1436004 [wandb_init.py:init():435] starting backend
2021-11-09 21:27:43,774 INFO    MainThread:1436004 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-09 21:27:43,886 INFO    MainThread:1436004 [backend.py:ensure_launched():199] starting backend process...
2021-11-09 21:27:43,951 INFO    MainThread:1436004 [backend.py:ensure_launched():204] started backend process with pid: 1437237
2021-11-09 21:27:43,953 INFO    MainThread:1436004 [wandb_init.py:init():444] backend started and connected
2021-11-09 21:27:43,962 INFO    MainThread:1436004 [wandb_init.py:init():503] updated telemetry
2021-11-09 21:27:44,299 INFO    MainThread:1436004 [wandb_init.py:init():533] communicating current version
2021-11-09 21:27:49,300 INFO    MainThread:1436004 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-11-09 21:28:19,301 INFO    MainThread:1436004 [interface_queue.py:_communicate_run():336] couldn't get run from backend
2021-11-09 21:28:19,308 ERROR   MainThread:1436004 [wandb_init.py:init():553] backend process timed out
2021-11-09 21:28:19,308 ERROR   MainThread:1436004 [wandb_init.py:init():562] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-11-09 21:28:30,834 INFO    MainThread:1436004 [wandb_init.py:teardown():205] tearing down wandb.init
